version: '3.8'

services:
  # Banco de dados PostgreSQL
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: barbearia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - barbearia-network

  # Backend API
  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_DATABASE: barbearia_db
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRE: 8h
      # Configurações SMTP (opcional para produção)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: your-email@gmail.com
      SMTP_PASS: your-app-password
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - barbearia-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - barbearia-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  barbearia-network:
    driver: bridge
