# EasyPanel Template Configuration
# Este arquivo define como sua aplicação será deployada no EasyPanel

version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-barbearia_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_NAME:-barbearia_db}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: 8h
      # SMTP Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Web App
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.barbearia.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.barbearia.loadbalancer.server.port=80"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
